model:
  model_path: "gpt2-xl"
  tokenizer_path: "gpt2-xl"
  model_type: "AccelerateILQLModel"
  num_layers_unfrozen: -1

train:
  seq_length: 768
  batch_size: 8
  epochs: 1000
  total_steps: 10000

  lr_init: 5.0e-5
  lr_target: 5.0e-5
  opt_betas: [0.9, 0.95]
  opt_eps: 1.0e-8
  weight_decay: 1.0e-6

  checkpoint_interval: 100000
  eval_interval: 100

  pipeline: "PromptPipeline"
  orchestrator: "OfflineOrchestrator"
  seed: 1000

method:
  name: "ilqlconfig"
  tau: 0.7
  gamma: 0.99
  cql_scale: 0.1
  awac_scale: 1
  alpha: 0.001
  steps_for_target_q_sync: 10
  betas: [4]
  two_qs: true
