train:
  seq_length: 768
  epochs: 1000
  total_steps: 10000
  batch_size: 16

  checkpoint_interval: 100000
  eval_interval: 1000

  pipeline: "PromptPipeline"
  orchestrator: "OfflineOrchestrator"

model:
  model_type: "AccelerateILQLModel"
  model_path: "gpt2-large"
  tokenizer_path: "gpt2"
  num_layers_unfrozen: 6

optimizer:
  name: "adamw"
  kwargs:
    lr: 5.0e-5
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 1.0e-6

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 10000 # train.total_steps
    eta_min: 8.0e-7

method:
  name: "ilqlconfig"
  tau: 0.7
  gamma: 0.99
  cql_scale: 0.1
  awac_scale: 1
  alpha: 0.001
  steps_for_target_q_sync: 5
  two_qs: true
  gen_kwargs:
    max_new_tokens: 64
    top_k: 20
    beta: 1
    temperature: 1.0
