default_config.yaml
[alex@ip-172-31-37-81 accelerate]$ cat default_config.yaml 
compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_hostfile: /fsx/alex/hostfiles/hosts_94
  deepspeed_multinode_launcher: openmpi
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  offload_optimizer_device: cpu
  offload_param_device: cpu
  zero3_init_flag: true
  zero3_save_16bit_model: false
  zero_stage: 3
distributed_type: DEEPSPEED
fsdp_config: {}
machine_rank: 0
main_process_ip: 172.31.234.58
main_process_port: 15004
main_training_function: main
mixed_precision: 'no'
num_machines: 2
num_processes: 16
use_cpu: false