compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: SIZE_BASED_WRAP
  fsdp_backward_prefetch_policy: BACKWARD_PRE
  min_num_params: 2000
  offload_params: false
  sharding_strategy: 1
machine_rank: 1
main_process_ip: 172.31.230.219
main_process_port: 15016
main_training_function: main
mixed_precision: 'no'
num_machines: 2
num_processes: 16
use_cpu: false