compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: FSDP
fsdp_config:
  fsdp_auto_wrap_policy: NO_WRAP
  fsdp_backward_prefetch_policy: NO_PREFETCH
  offload_params: true
  sharding_strategy: 1
machine_rank: 0
main_process_ip: 172.31.234.58
main_process_port: 15014
main_training_function: main
mixed_precision: 'no'
num_machines: 2
num_processes: 16
use_cpu: false