model:
  model_path: "stabilityai/stable-diffusion-2"
  tokenizer_path: None
  model_type: AccelerateSDModel
  num_layers_unfrozen: 2

train:
  total_steps: 0
  seq_length: None
  epochs: None
  batch_size: None
  lr_ramp_steps: None
  lr_decay_steps: None
  weight_decay: None 
  learning_rate_init: None
  learning_rate_target: None
  opt_betas: None
  checkpoint_interval: None
  eval_interval: None
  pipeline: None
  orchestrator: None
  checkpoint_dir: None
  project_name: None
  seed: 1000
  
method:
  name: 'diffppoconfig'
  img_size: [512, 512]
  num_rollouts: 4
  chunk_size: 4
  ppo_epochs: 4  # Number of ppo epochs
  init_kl_coef: 0.05  # init kl coefficient
  target: 6  # target kl coefficient, set None for fixed kl coef
  horizon: 10000  # PPO horizon
  gamma: 1  # PPO discount
  lam: 0.95  # PPO lambda
  cliprange: 0.2  # clip range
  cliprange_value: 0.2  # clip range
  vf_coef: 1  # value term weight
  scale_reward: False # False | "ref" | "running" estimate against which to scale rewards
  ref_mean: null
  ref_std: null # rescale rewards with this deviation
  cliprange_reward: 10