tune_config:
  mode: "max"
  metric: "metrics/sentiments"
  search_alg: "bohb"
  scheduler: "hyperbandforbohb"
  num_samples: 32
  max_concurrent_trials: 8

lr_init:
  strategy: "loguniform"
  values: [0.00001, 0.01]
tau:
  strategy: "uniform"
  values: [0.6, 0.95]
steps_for_target_q_sync:
  strategy: "choice"
  values: [1, 5, 10]
alpha:
  strategy: "loguniform"
  values: [0.001, 1.0]
